version: '3'

services:

  client:
    image: node:lts-bullseye
    hostname: client
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"